import numpy as np
import os
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from sklearn.metrics import (accuracy_score, precision_score,
                             recall_score, f1_score, confusion_matrix)
from sklearn.model_selection import StratifiedKFold
from statsmodels.stats.contingency_tables import mcnemar

# Store test-set predictions globally for McNemar's test
all_predictions = {}


# ─────────────────────────────────────────────────────────────────────────────
# Confusion matrix plot
# ─────────────────────────────────────────────────────────────────────────────

def save_confusion_matrix(cm, name):
    os.makedirs("results", exist_ok=True)
    plt.figure(figsize=(6, 5))
    plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
    plt.title(f"{name} Confusion Matrix", fontsize=14)
    plt.colorbar()
    classes    = ['Ham', 'Spam']
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, fontsize=11)
    plt.yticks(tick_marks, classes, fontsize=11)
    thresh = cm.max() / 2
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            plt.text(j, i, format(cm[i, j], 'd'),
                     ha="center", va="center",
                     color="white" if cm[i, j] > thresh else "black",
                     fontsize=12, fontweight='bold')
    plt.ylabel('Actual Label', fontsize=12)
    plt.xlabel('Predicted Label', fontsize=12)
    plt.tight_layout()
    path = f"results/{name}_cm.png"
    plt.savefig(path, dpi=300)
    plt.close()
    print(f"  Saved → {path}")


# ─────────────────────────────────────────────────────────────────────────────
# Threshold selection via out-of-fold CV (training set only)
# ─────────────────────────────────────────────────────────────────────────────

def find_threshold_oof(model, X_train, y_train, cv=5):
    """
    Find the optimal decision threshold using out-of-fold predictions
    generated by stratified k-fold cross-validation on the TRAINING set.

    The test set is never consulted during this step, eliminating the
    optimistic bias that arises from searching the threshold on held-out
    test data.

    Procedure:
      1. Split X_train into cv stratified folds.
      2. For each fold, refit the model on the remaining folds and
         generate probability scores for the held-out fold.
      3. Concatenate all out-of-fold scores to cover the full training set.
      4. Search 200 candidate thresholds over [0.2, 0.9] on these OOF
         scores, selecting the one maximising F1.
      5. Apply the +0.02 upward shift to further suppress false positives,
         capped at 0.95.

    Returns: optimal threshold (float)
    """
    import numpy as np
    from sklearn.model_selection import StratifiedKFold
    from sklearn.metrics import f1_score

    y_train = np.array(y_train)
    oof_scores = np.zeros(len(y_train))

    skf = StratifiedKFold(n_splits=cv, shuffle=True, random_state=42)

    for fold, (train_idx, val_idx) in enumerate(skf.split(X_train, y_train)):
        X_fold_train = X_train[train_idx]
        X_fold_val   = X_train[val_idx]
        y_fold_train = y_train[train_idx]

        model.fit(X_fold_train, y_fold_train)
        oof_scores[val_idx] = model.predict_proba(X_fold_val)[:, 1]

    # Search threshold on OOF scores — training set only
    best_t, best_f1 = 0.5, 0.0
    for t in np.linspace(0.2, 0.9, 200):
        preds = (oof_scores >= t).astype(int)
        f1    = f1_score(y_train, preds)
        if f1 > best_f1:
            best_f1 = f1
            best_t  = t

    # +0.02 upward shift to further reduce false positives
    return min(best_t + 0.02, 0.95)


# ─────────────────────────────────────────────────────────────────────────────
# Model evaluation
# ─────────────────────────────────────────────────────────────────────────────

def evaluate_model(name, model, X_train, y_train, X_test, y_test):
    """
    1. Find optimal threshold on out-of-fold predictions from X_train.
    2. Refit the model on the full X_train with the locked threshold.
    3. Apply the locked threshold to X_test — the test set is used
       only here, once, for final metric reporting.
    4. Compute accuracy, precision, recall, F1, FP, FN, FPR%.
    """
    global all_predictions

    # ── Step 1: threshold from OOF CV on training set ────────────────────────
    print(f"\n  [{name}] Searching threshold via 5-fold OOF CV...")
    threshold = find_threshold_oof(model, X_train, y_train, cv=5)
    print(f"  [{name}] Threshold locked at {threshold:.4f}")

    # ── Step 2: refit on full training set with best hyperparameters ──────────
    model.fit(X_train, y_train)

    # ── Step 3: apply locked threshold to test set ────────────────────────────
    test_scores = model.predict_proba(X_test)[:, 1]
    y_pred      = (test_scores >= threshold).astype(int)

    all_predictions[name] = y_pred      # for McNemar's test

    # ── Step 4: metrics ───────────────────────────────────────────────────────
    acc  = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec  = recall_score(y_test, y_pred)
    f1   = f1_score(y_test, y_pred)

    cm             = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()
    fpr_pct        = (fp / (fp + tn)) * 100

    print(f"\n{'='*55}")
    print(f"  {name}")
    print(f"{'='*55}")
    print(f"  Threshold (OOF CV)  : {threshold:.4f}")
    print(f"  Accuracy            : {acc*100:.2f}%")
    print(f"  Precision           : {prec*100:.2f}%")
    print(f"  Recall              : {rec*100:.2f}%")
    print(f"  F1-score            : {f1*100:.2f}%")
    print(f"  False Positives     : {fp}")
    print(f"  False Negatives     : {fn}")
    print(f"  FPR                 : {fpr_pct:.2f}%")
    print(f"  Confusion matrix  TN={tn}  FP={fp}")
    print(f"                    FN={fn}  TP={tp}")

    save_confusion_matrix(cm, name)

    return {
        "name":      name,
        "threshold": threshold,
        "accuracy":  acc,
        "precision": prec,
        "recall":    rec,
        "f1":        f1,
        "fp":        int(fp),
        "fn":        int(fn),
        "fpr_pct":   fpr_pct,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Table 7 — printed to console and saved
# ─────────────────────────────────────────────────────────────────────────────

def print_comparison_table(results_list):
    """
    Print Table 7 with FPR% column to console and save to results/table7.txt.
    results_list: list of dicts returned by evaluate_model(), in display order.
    """
    header = (f"{'Model':<25} {'Acc%':>6} {'Prec%':>7} {'Rec%':>6} "
              f"{'F1%':>6} {'FP':>5} {'FN':>5} {'FPR%':>6} {'Threshold':>10}")
    sep    = "-" * len(header)

    lines = [
        "\n\nTABLE 7 — Comparative Performance Summary",
        sep, header, sep
    ]

    for r in results_list:
        lines.append(
            f"{r['name']:<25} "
            f"{r['accuracy']*100:>6.2f} "
            f"{r['precision']*100:>7.2f} "
            f"{r['recall']*100:>6.2f} "
            f"{r['f1']*100:>6.2f} "
            f"{r['fp']:>5} "
            f"{r['fn']:>5} "
            f"{r['fpr_pct']:>6.2f} "
            f"{r['threshold']:>10.4f}"
        )

    lines.append(sep)
    output = "\n".join(lines)
    print(output)

    os.makedirs("results", exist_ok=True)
    with open("results/table7.txt", "w") as f:
        f.write(output + "\n")
    print("\nSaved → results/table7.txt")


# ─────────────────────────────────────────────────────────────────────────────
# McNemar's test
# ─────────────────────────────────────────────────────────────────────────────

def run_mcnemar_tests(y_test):
    """Run McNemar's test between all key model pairs."""

    pairs = [
        ("Naive_Bayes",   "SVM"),
        ("SVM",           "Hybrid_Base"),
        ("Hybrid_Base",   "Optimized_Hybrid"),
        ("Naive_Bayes",   "Optimized_Hybrid"),
        ("SVM",           "Optimized_Hybrid"),
    ]

    print("\n" + "=" * 60)
    print("MCNEMAR'S TEST RESULTS")
    print("=" * 60)

    os.makedirs("results", exist_ok=True)
    report_lines = []

    for model_a, model_b in pairs:
        if model_a not in all_predictions or model_b not in all_predictions:
            print(f"  Skipping {model_a} vs {model_b} — predictions missing")
            continue

        y_a = all_predictions[model_a]
        y_b = all_predictions[model_b]
        y_t = np.array(y_test)

        # Full contingency table for McNemar's test
        a = int(np.sum((y_a == y_t) & (y_b == y_t)))   # both correct
        b = int(np.sum((y_a == y_t) & (y_b != y_t)))   # A right, B wrong
        c = int(np.sum((y_a != y_t) & (y_b == y_t)))   # A wrong, B right
        d = int(np.sum((y_a != y_t) & (y_b != y_t)))   # both wrong

        table = [[a, b], [c, d]]
        exact = (b + c) < 25
        correction = not exact
        result = mcnemar(table, exact=exact, correction=correction)

        sig = "SIGNIFICANT" if result.pvalue < 0.05 else "NOT significant"

        print(f"\n  {model_a} vs {model_b}")
        print(f"    Both correct (a)     : {a}")
        print(f"    A right, B wrong (b) : {b}")
        print(f"    A wrong, B right (c) : {c}")
        print(f"    Both wrong (d)       : {d}")
        print(f"    Chi-square           : {result.statistic:.4f}")
        print(f"    P-value              : {result.pvalue:.4f}")
        print(f"    Result               : {sig}")

        report_lines.append(
            f"{model_a} vs {model_b}: chi2={result.statistic:.4f}, "
            f"p={result.pvalue:.4f}, a={a}, b={b}, c={c}, d={d}, {sig}"
        )

    with open("results/mcnemar_results.txt", "w") as f:
        f.write("McNemar's Test Results\n" + "=" * 60 + "\n")
        for line in report_lines:
            f.write(line + "\n")

    print("\nSaved → results/mcnemar_results.txt")