import numpy as np
from scipy.sparse import hstack, csr_matrix


def build_hybrid_features(nb_model, X_train, X_test):
    """
    Augment TF-IDF matrices with NB posterior probabilities and their
    log transforms, producing the enriched feature matrix X' of
    dimensionality d+4:

        X' = [X_tfidf | P(ham|x) | P(spam|x) | logP(ham|x) | logP(spam|x)]

    The NB model must already be fitted on X_train before calling this
    function. Posteriors for X_test are generated by applying the fitted
    model — no re-fitting occurs, preserving leakage prevention.
    """
    def _augment(X):
        probs     = nb_model.predict_proba(X)       # (n, 2) dense
        log_probs = np.log(probs + 1e-9)            # smoothed log transform
        return hstack([X,
                       csr_matrix(probs),
                       csr_matrix(log_probs)])

    X_train_hybrid = _augment(X_train)
    X_test_hybrid  = _augment(X_test)

    return X_train_hybrid, X_test_hybrid